name: CI
permissions: read-all

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          submodules: recursive

      - name: dprint
        uses: dprint/check@v2.3

      - name: rustfmt
        run: cargo fmt -v --check --all

      - name: clippy
        run: cargo clippy -rv --locked --all-targets --all-features

  test:
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          submodules: recursive

      - name: cargo test
        run: cargo test -rv
