name: CI
permissions: read-all

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  BOOST_VERSION: 1.83.0
  CARGO_TERM_COLOR: always

# For the available Boost versions per platform, see:
# https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: install boost
        uses: MarkusJx/install-boost@v2.5.1
        id: boost
        with:
          boost_version: ${{ env.BOOST_VERSION }}
          platform_version: 22.04

      - uses: actions/checkout@v5.0.0

      - name: dprint
        uses: dprint/check@v2.3

      - uses: actions-rust-lang/setup-rust-toolchain@v1.15.0
        with:
          components: clippy, rustfmt

      - name: clippy
        run: cargo clippy --locked --all-targets --all-features
        env:
          BOOST_ROOT: ${{ steps.boost.outputs.BOOST_ROOT }}

      - name: rustfmt Check
        uses: actions-rust-lang/rustfmt@v1.1.1

  test-ubuntu:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5.0.0

      - name: install boost
        uses: MarkusJx/install-boost@v2.5.1
        id: boost
        with:
          boost_version: ${{ env.BOOST_VERSION }}
          platform_version: 22.04

      - name: cargo build
        run: cargo build -rv
        env:
          BOOST_ROOT: ${{ steps.boost.outputs.BOOST_ROOT }}

      - name: cargo test
        run: cargo test -rv
        env:
          BOOST_ROOT: ${{ steps.boost.outputs.BOOST_ROOT }}

  test-macos:
    runs-on: macos-14
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5.0.0

      - name: install boost
        uses: MarkusJx/install-boost@v2.5.1
        id: boost
        with:
          boost_version: ${{ env.BOOST_VERSION }}
          platform_version: 14
          toolset: clang
          arch: aarch64

      - name: cargo build
        run: cargo build -rv
        env:
          BOOST_ROOT: ${{ steps.boost.outputs.BOOST_ROOT }}

      - name: cargo test
        run: cargo test -rv
        env:
          BOOST_ROOT: ${{ steps.boost.outputs.BOOST_ROOT }}

  test-windows:
    runs-on: windows-2022
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        toolset: [mingw, msvc]
    steps:
      - uses: actions/checkout@v5.0.0

      - name: install boost
        uses: MarkusJx/install-boost@v2.5.1
        id: boost
        with:
          boost_version: ${{ env.BOOST_VERSION }}
          platform_version: 2022
          toolset: ${{ matrix.toolset }}

      - name: cargo build
        run: cargo build -rv
        env:
          BOOST_ROOT: ${{ steps.boost.outputs.BOOST_ROOT }}

      - name: cargo test
        run: cargo test -rv
        env:
          BOOST_ROOT: ${{ steps.boost.outputs.BOOST_ROOT }}
